### ISSUE TITLE
session storage not defined

### ISSUE THREAD

**Issue by dalipkumar703** [juliancwirko/meteor-schat-client-core#1]
ReferenceError: sessionStorage is not defined
W20170710-11:03:49.473(5.5)? (STDERR)     at Object.sChat.init (packages/schat:client-core/client-core.js:31:30)
W20170710-11:03:49.474(5.5)? (STDERR)     at server/main.js:5:9
W20170710-11:03:49.475(5.5)? (STDERR)     at Function.time (/home/dalip/Desktop/web-chat/.meteor/local/build/programs/server/profile.js:309:28)
W20170710-11:03:49.476(5.5)? (STDERR)     at /home/dalip/Desktop/web-chat/.meteor/local/build/programs/server/boot.js:347:13
W20170710-11:03:49.478(5.5)? (STDERR)     at /home/dalip/Desktop/web-chat/.meteor/local/build/programs/server/boot.js:388:5
W20170710-11:03:49.479(5.5)? (STDERR)     at Function.run (/home/dalip/Desktop/web-chat/.meteor/local/build/programs/server/profile.js:510:12)
W20170710-11:03:49.480(5.5)? (STDERR)     at /home/dalip/Desktop/web-chat/.meteor/local/build/programs/server/boot.js:386:11

**Comment by juliancwirko** [comment]
Hi, try now, version 1.2.1

**Comment by dalipkumar703** [comment]
Thanks for response :) 
But it showing same error again.

**Comment by juliancwirko** [comment]
sorry, I thought that this is related to the meteor's session package ;) But this is related to native sessionStorage. It should run only on the client side, this is why there is a bug. I need to test it because I haven't used it very long.

**Comment by dalipkumar703** [comment]
OK Julian. Thanks
I will wait ...

**Comment by juliancwirko** [comment]
Everything seems to work on my side. You need to be sure that you run all the configuration on the client side. I mean this (example):
```
Meteor.startup(function () {
    sChat.init('JMSZtbT2RdNrPYYRi', {
        ssl: true,
        welcomeMessage: 'Hi, how can I help you?',
        hostName: 'www.simplechat.support',
        labels: {
            sendPlaceholder: 'Send the message...',
            headerTitle: 'Welcome on my website!'
        }
    });
});
```

**Comment by dalipkumar703** [comment]
Great julian. It's working correctly .Actually i added startup code in server side. Thanks a lot . One more thing is it necessary to put hostname (SimpleChat.Support) or we can put something else.

**Comment by juliancwirko** [comment]
If you'll host your own SimpleChat instance you need to change it to your hostname. Otherwise you need to have an account on simplechat.support and connect your client app to that. Check out docs: 

- https://www.simplechat.support/docs#free-option
- https://www.simplechat.support/docs#self-hosted-option

**Comment by dalipkumar703** [comment]
Ok. How to remove powered by www.simplechat.support :) ?

**Comment by juliancwirko** [comment]
For now there isn't a simple way because this is a package designed 
specially for hosted SimpleChat.Support app. But you can do that.
You would need to clone https://github.com/juliancwirko/meteor-schat-client-blaze package into packages folder and then remove this section: https://github.com/juliancwirko/meteor-schat-client-blaze/blob/master/client-blaze.html#L22

**Comment by dalipkumar703** [comment]
Ok julian. Thanks a lot :) .
